import jsPDF from 'jspdf';
import { User, Goal, DailyLogs, UserStats } from '../types';

export const generatePDFReport = (
  user: User, 
  goals: Goal[], 
  logs: DailyLogs, 
  stats: UserStats,
  currentMonth: Date
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const monthName = currentMonth.toLocaleString('default', { month: 'long', year: 'numeric' });

  // -- Header --
  doc.setFillColor(79, 70, 229); // Indigo-600
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text("OrbitGoals Monthly Report", 20, 25);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`${monthName}`, pageWidth - 20, 25, { align: 'right' });

  // -- User Profile --
  let yPos = 55;
  doc.setTextColor(51, 65, 85); // Slate-700
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("Pilot Profile", 20, yPos);
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${user.name}`, 20, yPos);
  doc.text(`Current Level: ${stats.level}`, 100, yPos);
  yPos += 7;
  doc.text(`Total XP: ${stats.totalPoints}`, 20, yPos);
  doc.text(`Longest Streak: ${stats.currentStreak} days`, 100, yPos);

  // -- Executive Summary --
  yPos += 15;
  doc.setDrawColor(203, 213, 225); // Slate-300
  doc.line(20, yPos, pageWidth - 20, yPos);
  
  yPos += 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("Performance Summary", 20, yPos);
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const completionRate = stats.totalCompleted > 0 
    ? Math.round((stats.totalCompleted / (goals.length * 30)) * 100) // Rough estimate
    : 0;

  const summaryText = [
    `This month you completed a total of ${stats.totalCompleted} tasks across ${goals.length} active goals.`,
    `You achieved ${stats.perfectDays} perfect days where all goals were met.`,
    `Your overall consistency score is approximately ${completionRate}%.`
  ];
  
  doc.text(summaryText, 20, yPos);

  // -- Habit Breakdown --
  yPos += 25;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("Habit Breakdown", 20, yPos);
  yPos += 10;

  // Simple Table Header
  doc.setFillColor(241, 245, 249); // Slate-100
  doc.rect(20, yPos, pageWidth - 40, 10, 'F');
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text("Goal", 25, yPos + 7);
  doc.text("Completed", 100, yPos + 7);
  doc.text("Success Rate", 160, yPos + 7);
  
  yPos += 12;
  doc.setTextColor(51, 65, 85);

  const currentMonthPrefix = currentMonth.toISOString().slice(0, 7);
  
  goals.forEach(goal => {
    let completed = 0;
    let totalDays = 0;
    
    Object.keys(logs).forEach(dateStr => {
      if (dateStr.startsWith(currentMonthPrefix)) {
        totalDays++;
        if (logs[dateStr][goal.id] === 'completed') completed++;
      }
    });
    
    const rate = totalDays > 0 ? Math.round((completed/totalDays)*100) : 0;
    
    doc.text(goal.title, 25, yPos);
    doc.text(`${completed} times`, 100, yPos);
    doc.text(`${rate}%`, 160, yPos);
    
    // Progress bar visualization
    doc.setFillColor(226, 232, 240); // bg
    doc.rect(25, yPos + 2, 160, 2, 'F');
    doc.setFillColor(16, 185, 129); // green
    doc.rect(25, yPos + 2, 1.6 * rate, 2, 'F');

    yPos += 10;
  });

  // -- Recommendations --
  yPos += 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("AI Coach Recommendations", 20, yPos);
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(100, 116, 139);
  doc.text("Based on your logs, focus on improving your weekend consistency.", 20, yPos);
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by OrbitGoals Premium", pageWidth / 2, 280, { align: 'center' });

  doc.save(`OrbitGoals_Report_${monthName}.pdf`);
};